# Proxmox hosts inventory
[proxmox]
10.10.11.47 ansible_user=root
10.10.11.52 ansible_user=root
10.10.11.53 ansible_user=root
10.10.11.55 ansible_user=root
10.10.11.57 ansible_user=root

[proxmox:vars]
# Variables for all proxmox hosts
config_repo_url: https://github.com/deepwatrcreatur/unified-nix-configuration.git
config_repo_branch: main
config_repo_path: /root/flakes/unified-nix-configuration
home_manager_output: proxmox-root
