# Proxmox baseline for inference1.
# Plain OVMF only. Do not add efidisk0. Do not enable Secure Boot.
# Keep exactly one installer ISO attached during bootstrap.

agent: 1
serial0: socket
bios: ovmf
boot: order=ide0;scsi0
cores: 8
cpu: host
ide0: local:iso/nixos-graphical-25.11.7198.71caefce12ba-x86_64-linux.iso,media=cdrom
machine: q35
memory: 46080
name: inference1
net0: virtio=BC:24:11:E4:45:B0,bridge=vmbr0
ostype: l26
scsi0: rpool-data:vm-103-disk-4,size=200G
scsihw: virtio-scsi-single
smbios1: uuid=770efe11-26de-4b9d-89d9-f4ec6168236b
sockets: 1
usb0: host=413c:2003
vmgenid: 7c31836f-b089-4872-8532-470d4d1255f2
